spring:
  profiles:
    active: local

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SMTP_ADDRESS}
    password: ${MAIL_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
