spring:
  application:
    name: user
  profiles:
    active: local
  config:
    import: optional:configserver:http://admin:1234@localhost:9000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true