server:
  port: 8075

spring:
  application:
    name: user
  profiles:
    active: local
  config:
    import: optional:configserver:http://admin:1234@localhost:9000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: feagegawgaekljflkahgiklwbfgalogbnalkdnioraqsdfge
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka