version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: qwer
      MYSQL_DATABASE: ecommerce_service
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq-delay:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "25672:15672"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - my-network

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - my-network

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    container_name: config-server
    ports:
      - "9000:9000"
    networks:
      - my-network

  gateway-server:
    build:
      context: .
      dockerfile: gateway-server/Dockerfile
    container_name: gateway-server
    environment:
      EUREKA_SERVER_URL: http://admin:1234@eureka-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - my-network

  user-service:
    build:
      context: .
      dockerfile: user/Dockerfile
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ecommerce_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: qwer
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: local
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      EUREKA_SERVER_URL: http://admin:1234@eureka-server:8761/eureka/
    ports:
      - "8081:8080"
    depends_on:
      - eureka-server
      - mysql-db
      - config-server
      - redis
    networks:
      - my-network

  product-service:
    build:
      context: .
      dockerfile: product/Dockerfile
    container_name: product-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ecommerce_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: qwer
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: local
      EUREKA_SERVER_URL: http://admin:1234@eureka-server:8761/eureka/
    ports:
      - "8076:8076"
    depends_on:
      - eureka-server
      - mysql-db
      - config-server
      - redis
    networks:
      - my-network

  order-service:
    build:
      context: .
      dockerfile: order/Dockerfile
    container_name: order-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ecommerce_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: qwer
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: local
      EUREKA_SERVER_URL: http://admin:1234@eureka-server:8761/eureka/
    ports:
      - "8077:8077"
    depends_on:
      - eureka-server
      - mysql-db
      - config-server
      - redis
    networks:
      - my-network

  payment-service:
    build:
      context: .
      dockerfile: payment/Dockerfile
    container_name: payment-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ecommerce_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: qwer
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: local
      EUREKA_SERVER_URL: http://admin:1234@eureka-server:8761/eureka/
    ports:
      - "8078:8078"
    depends_on:
      - eureka-server
      - mysql-db
      - config-server
      - rabbitmq
    networks:
      - my-network

volumes:
  mysql-data:
  rabbitmq_data:
  redis-data:

networks:
  my-network:
    driver: bridge
