version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: qwer
      MYSQL_DATABASE: ecommerce_service
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  user-service:
    build:
      context: .
      dockerfile: user/Dockerfile
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ecommerce_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: qwer
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge
